-- STREETFIT BUSINESS MANAGER - SUPABASE SCHEMA (USERNAME-BASED AUTH)

-- 1. Create Profiles Table
CREATE TABLE IF NOT EXISTS profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  email TEXT UNIQUE,
  role TEXT DEFAULT 'partner' CHECK (role IN ('admin', 'partner')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Ensure username column exists (in case table was created previously without it)
DO $$ 
BEGIN 
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='profiles' AND column_name='username') THEN
    ALTER TABLE public.profiles ADD COLUMN username TEXT UNIQUE;
  END IF;
END $$;

-- 2. Contributions Table
CREATE TABLE IF NOT EXISTS contributions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  partner_id UUID REFERENCES profiles(id) NOT NULL,
  amount NUMERIC NOT NULL DEFAULT 0,
  date DATE DEFAULT CURRENT_DATE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Expenses Table
CREATE TABLE IF NOT EXISTS expenses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description TEXT NOT NULL,
  amount NUMERIC NOT NULL DEFAULT 0,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  partner_id UUID REFERENCES profiles(id) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Plans Table
CREATE TABLE IF NOT EXISTS plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  estimated_cost NUMERIC NOT NULL DEFAULT 0,
  actual_cost NUMERIC,
  phase TEXT DEFAULT 'Phase 1',
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'completed')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Enable Row Level Security (RLS)
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE contributions ENABLE ROW LEVEL SECURITY;
ALTER TABLE expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE plans ENABLE ROW LEVEL SECURITY;

-- 6. RLS Policies
DROP POLICY IF EXISTS "Public profiles viewable" ON profiles;
CREATE POLICY "Public profiles viewable" ON profiles FOR SELECT USING (true);

-- Contributions: Public can view, only ADMIN can insert
DROP POLICY IF EXISTS "Public can view contributions" ON contributions;
CREATE POLICY "Public can view contributions" ON contributions FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admin can add contributions" ON contributions;
CREATE POLICY "Admin can add contributions" ON contributions FOR INSERT WITH CHECK (
  EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin')
);

-- Expenses: Everyone can view, anyone LOGGED IN can add
DROP POLICY IF EXISTS "Public view expenses" ON expenses;
CREATE POLICY "Public view expenses" ON expenses FOR SELECT USING (true);

DROP POLICY IF EXISTS "Authenticated add expenses" ON expenses;
CREATE POLICY "Authenticated add expenses" ON expenses FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "Admin update expenses" ON expenses;
CREATE POLICY "Admin update expenses" ON expenses FOR UPDATE USING (
  EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin')
);

-- Plans: Everyone can view/add, only admin can complete
DROP POLICY IF EXISTS "Public view plans" ON plans;
CREATE POLICY "Public view plans" ON plans FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public add plans" ON plans;
CREATE POLICY "Public add plans" ON plans FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Admin update plans" ON plans;
CREATE POLICY "Admin update plans" ON plans FOR UPDATE USING (
  EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin')
);

-- 7. Trigger for Profile Creation
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
DECLARE
  is_first_user BOOLEAN;
  final_username TEXT;
BEGIN
  -- Check if this is the first user
  SELECT NOT EXISTS (SELECT 1 FROM public.profiles) INTO is_first_user;
  
  -- Extract username from metadata, or fallback to email part
  final_username := COALESCE(
    new.raw_user_meta_data->>'username', 
    split_part(new.email, '@', 1)
  );

  -- Insert profile, ignore if ID already exists
  INSERT INTO public.profiles (id, email, username, role)
  VALUES (
    new.id, 
    new.email, 
    final_username,
    CASE WHEN is_first_user THEN 'admin' ELSE 'partner' END
  )
  ON CONFLICT (id) DO NOTHING;
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
-- 8. Settings Table (For Global Config like target budget)
CREATE TABLE IF NOT EXISTS settings (
  key TEXT PRIMARY KEY,
  value NUMERIC NOT NULL DEFAULT 0,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert default target budget
INSERT INTO settings (key, value) VALUES ('target_budget', 0) ON CONFLICT (key) DO NOTHING;

-- RLS for Settings
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public view settings" ON settings;
CREATE POLICY "Public view settings" ON settings FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admin update settings" ON settings;
CREATE POLICY "Admin update settings" ON settings FOR UPDATE USING (
  EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin')
);

-- 9. DELETE POLICIES (Crucial for CRUD)
-- Allow admins to delete from any table
CREATE POLICY "Admin delete profiles" ON profiles FOR DELETE USING (
  EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin')
);

CREATE POLICY "Admin delete contributions" ON contributions FOR DELETE USING (
  EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin')
);

CREATE POLICY "Admin delete expenses" ON expenses FOR DELETE USING (
  EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin')
);

CREATE POLICY "Admin delete plans" ON plans FOR DELETE USING (
  EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin')
);
